spring.application.name=backend

# Banco de dados PostgreSQL - Render
spring.datasource.url=jdbc:postgresql://dpg-daq6rbh7lnhs73bsluvg-a.oregon-postgres.render.com/docflow_5f5i
spring.datasource.username=docflow_5f5i_user
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=chave-secreta-do-docflow-para-desenvolvimento-2026
jwt.expiration=86400000